### ISSUE TITLE
Refactor events

### ISSUE THREAD

**Issue by fedormalinin** [jumpeebunee/meet-and-go#4]
1. Show me as participant of meeting
2. Change button "Continue" on "Description" and "Cancel" on "Close"

![image](https://user-images.githubusercontent.com/106557249/216803809-8c5c2d49-eee9-4b72-a3ab-1a81399c7a9a.png)

**Comment by jumpeebunee** [comment]
1. Add avatar if user register to event.
2. Changed title for buttons.
