### ISSUE TITLE
List of participants

### ISSUE THREAD

**Issue by fedormalinin** [jumpeebunee/meet-and-go#9]
List of participants in event like this:
![426346](https://user-images.githubusercontent.com/106557249/216823274-1ec2d0c1-80e1-4704-8e6f-a02e1d3d4ccc.jpg)

should open profiles by click

**Comment by jumpeebunee** [comment]
fixed 
![image](https://user-images.githubusercontent.com/105386597/216969462-f34fd1e0-7539-4c9d-b0d0-cfb99116c3ab.png)
